const constants = {
    ADD_SPORT: "ADD_SPORT",
    REMOVE_SPORT: "REMOVE_SPORT",
    ADD_WORK: "ADD_WORK",
    REMOVE_WORK: "REMOVE_WORK",
    ADD_ENTERTAINMENT: "ADD_ENTERTAINMENT",
    REMOVE_ENTERTAINMENT: "REMOVE_ENTERTAINMENT",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT"
}

export default constants
